languageCode = "en-us"
baseurl = "https://unfolding-protons.netlify.com/"
title = "Unfolding protons"
theme = "cocoa"

[params]
author = "Vincent Ko"
selfintro = "Unfolding protons"
avatar    = "img/profile.png"
