languageCode = "en-us"
baseurl = "https://kobl.one/"
title = "An Ethereum and blockchain blog"
theme = "cocoa"
disqusShortname = "unfolding-protons"
googleAnalytics = "UA-92190076-1"

[params]
author = "Vincent Kō"
selfintro = "Unfolding Protons - A blog about Ethereum and blockchains"
avatar = "img/profile.png"
# linkedin = "//linkedin.com/in/vincentkobel"
github = "//github.com/vkobel"
highlightjs = true
email = "blog@kobl.one"
